### ISSUE TITLE
How to specify the path of sa.exe and start the game ?

### ISSUE THREAD

**Issue by kirtan95** [P3ti/RakSAMP#4]
I can successfully compile and run both server and client. 

However, i don't see any instructions to link the RakSAMPclient.exe to San Andreas binary, so we could actually join the hosted game.

**Comment by P3ti** [comment]
RakSAMPClient has nothing to do with San Andreas binary.

**Comment by kirtan95** [comment]
Okay, so After i compile and execute RakSAMPClient, and connect it to server, then all i can see is the chat like interface in which i can execute various commands. Can't we play the actual san andreas with it? Like hooking the client to san andreas binary?

**Comment by P3ti** [comment]
RakSAMPClient isn't intended to replace the original SA-MP client, however you can start building an alternative client/server based on RakSAMP or take the old leaked source code and update it.
